// <auto-generated />
using System;
using BitcoinApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BitcoinApi.Data.Migrations
{
    [DbContext(typeof(BitcoinApiDbContext))]
    partial class BitcoinApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BitcoinApi.Data.TransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<decimal>("Amount");

                    b.Property<string>("BlockHash")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<int>("BlockIndex");

                    b.Property<int>("BlockTime");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<int>("Confirmations");

                    b.Property<string>("Label")
                        .HasMaxLength(400);

                    b.Property<int>("Time");

                    b.Property<int>("TimeReceived");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.HasKey("Id");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("BitcoinApi.Data.WalletEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<decimal>("Balance");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("Removed");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.ToTable("wallets");
                });
#pragma warning restore 612, 618
        }
    }
}
